"""empty message

Revision ID: 4b2ad1037435
Revises: 4fe9cf0e29f7
Create Date: 2024-04-27 13:48:50.209388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b2ad1037435'
down_revision = '4fe9cf0e29f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index('ix_student_group')
        batch_op.create_index(batch_op.f('ix_student_group'), ['group'], unique=False)
        batch_op.drop_index('ix_student_name')
        batch_op.create_index(batch_op.f('ix_student_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_name'))
        batch_op.create_index('ix_student_name', ['name'], unique=1)
        batch_op.drop_index(batch_op.f('ix_student_group'))
        batch_op.create_index('ix_student_group', ['group'], unique=1)

    # ### end Alembic commands ###
